#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/studentPortalBonafide
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
